Games/Models/ViewModel/LayoutView.cs
using Games.Models.Entity;
using Games.Models.Repository;
using System.Collections.Generic;

namespace Games.Models.ViewModel {

    public class LayoutView {
        public List<platform> listaPlatform;
        public List<int> ativos;
        public int total_colecao;
        public int total_wishlist;
        public int total_watchlist;
        public int total_plus;
        public List<Totais> totais;
        private static LayoutView view;

        private LayoutView() { }

        public static LayoutView GetLayoutView() {
            if (view == null) {
                init();
            }
            return view;
        }

        public class Totais {
            public string plataforma;
            public string status;
            public int total;
        }

        public static LayoutView init() {
            GameRepository gr = new GameRepository();
            PlatformRepository platformRepository = new PlatformRepository();

            view = new LayoutView();
            view.ativos = new List<int>();
            view.totais = new List<Totais>();

            Dictionary<string, int> total = gr.GetTotalJogosStatus();
            List<game_platform> jogos = gr.GetListaGeral();
            view.listaPlatform = platformRepository.Listar();
            
            view.total_colecao = total["Coleção"];
            view.total_wishlist = total["Wishlist"];
            view.total_watchlist = total["Watchlist"];
            view.total_plus = total["Plus"];
            
            foreach (platform plat in view.listaPlatform) {
                view.totais.Add(new Totais {
                        plataforma = plat.sigla,
                        status = "colecao",
                        total = jogos.FindAll(j => (j.id_status == 1) && (j.platform.sigla == plat.sigla)).Count
                    });
                view.totais.Add(new Totais {
                    plataforma = plat.sigla,
                    status = "wishlist",
                    total = jogos.FindAll(j => (j.id_status == 2) && (j.platform.sigla == plat.sigla)).Count
                });
                view.totais.Add(new Totais {
                    plataforma = plat.sigla,
                    status = "watchlist",
                    total = jogos.FindAll(j => (j.id_status == 3) && (j.platform.sigla == plat.sigla)).Count
                });
                view.totais.Add(new Totais {
                    plataforma = plat.sigla,
                    status = "plus",
                    total = jogos.FindAll(j => (j.id_status == 4) && (j.platform.sigla == plat.sigla)).Count
                });
            }

            return view;
        }
    }

}

Games/Controllers/JqueryController.cs
using FluentMetacritic;
using Games.Models.Entity;
using Games.Models.Repository;
using Games.Models.Validacao;
using Games.Models.ViewModel;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Services;
using Google.Apis.Sheets.v4;
using Google.Apis.Sheets.v4.Data;
using Google.Apis.Util.Store;
using Igdb.ResponseModels;
using Igdb.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using static Games.Models.ViewModel.GameListView;

namespace Games.Controllers {
    public class JqueryController : BaseController {

        public ActionResult MenuPlataformas(int? plataforma) {
            if (plataforma.HasValue) {
                layoutView.ativos = new List<int>();
                layoutView.ativos.Add(plataforma.Value);
            }
            return PartialView("PlatformMenuView", layoutView);
        }

        public ActionResult Menu() {
            return PartialView("MenuView", layoutView);
        }

        public ActionResult ListaJogosIndex(string status) {
            string tipo = null;
            GameRepository gameRepository = new GameRepository();
            GameListView view = new GameListView();

            switch (status) {
                case "wishlist":
                    view.ListaJogos = gameRepository.ListarJogosWishlist(layoutView.ativos);
                break;
                case "watchlist":
                    view.ListaJogos = gameRepository.ListarJogos(layoutView.ativos, 3);
                break;
                default:
                    view.ListaJogos = gameRepository.ListarJogos(layoutView.ativos, (int)Enum.Parse(typeof(GameListView.status), status));
                break;
            }

            if (tipo == null) {
                switch (status) {
                    case "colecao":
                    case "plus":
                        tipo = "GameGridView";
                    break;
                    case "wishlist":
                    case "watchlist":
                        tipo = "GameListView";
                    break;
                }
            }
            return PartialView(tipo, view);
        }

        [HttpPost]
        public ActionResult BuscarJogoIgdbJquery(string search) {
            IgdbService igdb = new IgdbService();
            GameResultView view = new GameResultView();

            view.ListaJogos = igdb.BuscarJogo(search);

            return PartialView("GameResultView", view);
        }

        [HttpPost]
        public ActionResult BuscarJogoEntityJquery(string search) {
            GameRepository gameRepository = new GameRepository();
            BuscaResultView view = new BuscaResultView();

            view.ListaJogosEntity = gameRepository.BuscarJogos(search);

            return PartialView("BuscaResultView", view);
        }

        [HttpPost]
        public ActionResult ExibirFormGame() {
            return PartialView("FormGameView", GameDataView.init());
        }
        
        [HttpPost]
        public JsonResult SalvarNovoJogoJquery(GameDataView dados) {
            ValidacaoGameMessage validacao = ValidacaoGameService.Validar(dados);
            if (validacao.Valido) {
                GameRepository gameRepository = new GameRepository();
                gameRepository.Adicionar(dados);
            }
            return Json(validacao);
        }

        [HttpPost]
        public JsonResult AlterarJogoJquery(GameDataView dados) {
            ValidacaoGameMessage validacao = ValidacaoGameService.Validar(dados);
            if (validacao.Valido) {
                GameRepository gameRepository = new GameRepository();
                gameRepository.Alterar(dados);
            }
            return Json(validacao);
        }

        [HttpPost]
        public void AtualizarOrdemWishlistJquery(int game, int posicao) {
            GameRepository gameRepository = new GameRepository();
            gameRepository.AtualizarOrdemWishlist(game, posicao);
        }

        [HttpPost]
        public void ExcluirJogoJquery(int id) {
            GameRepository gameRepository = new GameRepository();
            GameEntity game = gameRepository.BuscarDados(id);

            gameRepository.Excluir(game);
        }

        [HttpPost]
        public ActionResult RemoverPlataformaJquery(int index) {
            GameDataView view = GameDataView.GetGameDataView();
            view.Platforms.RemoveAt(index);
            return PartialView("PlatformStatusView", view);
        }

        [HttpPost]
        public ActionResult AdicionarPlataformaJquery() {
            GameDataView view = GameDataView.GetGameDataView();
            view.Platforms.Add(new game_platform());
            return PartialView("PlatformStatusView", view);
        }

        [HttpPost]
        public async Task<ActionResult> PreencherDadosGameIgdbJquery(int id_igdb, int Id = 0) {
            IgdbService igdb = new IgdbService();
            DadosGameResponse response = igdb.DadosJogo(id_igdb).FirstOrDefault();
            List<DadosDeveloperPublisherResponse> devs = new List<DadosDeveloperPublisherResponse>();
            List<DadosDeveloperPublisherResponse> pubs = new List<DadosDeveloperPublisherResponse>();
            List<DadosGenreResponse> genres = new List<DadosGenreResponse>();
            List<ReleaseDate> lancamentos = new List<ReleaseDate>();

            PlatformRepository pr = new PlatformRepository();

            if (response.Developers != null && response.Developers.Count > 0) {
                devs = igdb.DadosDeveloperPublisher(response.Developers.ToArray());
            }
            if (response.Publishers != null && response.Publishers.Count > 0) {
                pubs = igdb.DadosDeveloperPublisher(response.Publishers.ToArray());
            }
            if (response.Genres != null && response.Genres.Count > 0) {
                genres = igdb.DadosGenre(response.Genres.ToArray());
            }
            if (response.ReleaseDates != null && response.ReleaseDates.Count > 0) {
                lancamentos = response.ReleaseDates;
            }

            GameDataView gameDataView = GameDataView.GetGameDataView();
            gameDataView.Id = Id;
            gameDataView.id_igdb = id_igdb;
            gameDataView.Titulo = response.Name;
            gameDataView.Descricao = response.Summary;

            if (response.Cover != null) {
                gameDataView.Imagem = gameDataView.BigCoverUrl + response.Cover.CloudinaryId + ".jpg";
                gameDataView.CloudnaryId = response.Cover.CloudinaryId;
            }
            else {
                gameDataView.Imagem = "/Content/ps.png";
            }

            gameDataView.InitListas();

            foreach (DadosDeveloperPublisherResponse dev in devs) {
                gameDataView.ListaDeveloper.Add(new developerPublisher {
                    name = dev.Name,
                    id_igdb = dev.Id
                });
            }

            foreach (DadosDeveloperPublisherResponse pub in pubs) {
                gameDataView.ListaPublisher.Add(new developerPublisher {
                    name = pub.Name,
                    id_igdb = pub.Id
                });
            }

            foreach (DadosGenreResponse genre in genres) {
                gameDataView.ListaGenre.Add(new genre {
                    id_igdb = genre.Id,
                    name = genre.Name
                });
            }

            try {
                var buscaMetacritic = await Metacritic.SearchFor().Games().UsingTextAsync(response.Name);

                foreach (ReleaseDate lancamento in lancamentos) {
                    platform plataforma = pr.GetPlatformByIgdb(lancamento.Platform);
                    int? meta = null;
                    if (plataforma != null) {
                        string sigla;
                        switch (plataforma.sigla) {
                            case "PS1":
                                sigla = "PS";
                            break;
                            case "PSVITA":
                                sigla = "VITA";
                            break;
                            default:
                                sigla = plataforma.sigla;
                            break;
                        }

                        var resultado = buscaMetacritic.Where(m => m.Platform == sigla).Where(m => m.Name.ToLowerInvariant() == response.Name.ToLowerInvariant()).FirstOrDefault();
                        if (resultado != null) {
                            meta = resultado.Score;
                        }

                        DateTime data = new DateTime(1970, 1, 1, 0, 0, 0).AddSeconds(Convert.ToDouble(Convert.ToDouble(lancamento.Date)));
                        gameDataView.Platforms.Add(new game_platform {
                            id_platform = plataforma.id,
                            release_date = data,
                            metacritic = meta,
                            id_region = lancamento.Region
                        });
                    }
                }
            }
            catch (Exception ex) {

            }

            return PartialView("FormGameView", gameDataView);
        }

        [HttpPost]
        public ActionResult PreencherDadosGameEntityJquery(int id) {
            GameRepository gameRepository = new GameRepository();
            DeveloperPublisherRepository devPubRepository = new DeveloperPublisherRepository();
            GameEntity game = gameRepository.BuscarDados(id);

            List<game_developerPublisher> devs = game.game_developerPublisher.Where(d => d.tipo == (int)GameDataView.tipoDeveloperPublisher.Developer).ToList();
            List<game_developerPublisher> pubs = game.game_developerPublisher.Where(p => p.tipo == (int)GameDataView.tipoDeveloperPublisher.Publisher).ToList();

Games/Views/Shared/MenuView.cshtml
@model Games.Models.ViewModel.LayoutView
<ul class="nav navbar-nav">
    <li class="li_dashboard">
        <a href="@Url.Action("dashboard", "Home")">Dashboard</a></li>
    <li>
        <a href="@Url.Action("Index/colecao", "Home")">
            Coleção
            <span class="fa-stack">
                <i class="fa fa-circle fa-stack-2x circulo"></i>
                <span class="fa-stack-1x icon-text">@Model.total_colecao</span>
            </span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index/wishlist", "Home")">
            Wishlist
            <span class="fa-stack">
                <i class="fa fa-circle fa-stack-2x circulo"></i>
                <span class="fa-stack-1x icon-text">@Model.total_wishlist</span>
            </span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index/watchlist", "Home")">
            Watchlist
            <span class="fa-stack">
                <i class="fa fa-circle fa-stack-2x circulo"></i>
                <span class="fa-stack-1x icon-text">@Model.total_watchlist</span>
            </span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index/plus", "Home")">
            Plus
            <span class="fa-stack">
                <i class="fa fa-circle fa-stack-2x circulo"></i>
                <span class="fa-stack-1x icon-text">@Model.total_plus</span>
            </span>
        </a>
    </li>
</ul>

Games/Views/Shared/PlatformMenuView.cshtml
@model Games.Models.ViewModel.LayoutView
<script>
    /*========== menu de plataformas ================*/
    //atualizar menu de plataformas e lista de jogos
    $("#MenuPlataforma").off().on("click",".li_plataforma",function () {
        var element = $(this);
        $(".li_plataforma").each(function () {
            $(this).removeClass("ativo");
        });
        element.addClass("ativo");
        $.post('@Url.Action("MenuPlataformas", "Jquery")', { plataforma: element.attr("id") },
        function (resposta) {
            $("#MenuPlataforma").html(resposta);
            $.post('@Url.Action("ListaJogosIndex", "Jquery")', { status: status },
            function (resposta) {
                $("#GameListView").html(resposta);
            });
        });
    });
</script>
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">Plataformas</li>
        @{string classe_todas = "li_plataforma";}
        @if (Model.ativos.IndexOf(0) != -1) {
            classe_todas = "li_plataforma ativo";
        }
        <li class="@classe_todas" id="0">
            Todas as plataformas
            <span class="fa-stack circulo-sidebar">
                <i class="fa fa-circle fa-stack-2x"></i>
                <span class="fa-stack-1x icon-text">
                    @Model.totais.Where(t => t.status == ViewContext.RouteData.Values["status"].ToString()).Sum(t => t.total)
                </span>
            </span>
        </li>
        @foreach (var platform in Model.listaPlatform) {
            string classe = "li_plataforma";
            if (Model.ativos.IndexOf(platform.id) != -1) {
                classe = "li_plataforma ativo";
            }
            <li class="@classe" id="@platform.id">
                @platform.name
                <span class="fa-stack circulo-sidebar">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <span class="fa-stack-1x icon-text">
                        @Model.totais.Where(t => t.plataforma == platform.sigla).Where(t => t.status == ViewContext.RouteData.Values["status"].ToString()).FirstOrDefault().total
                    </span>
                </span>
            </li>
        }
    </ul>
</div>

Games/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title</title>
        <link rel="icon" href="@Url.Content("~/favicon.ico")" type="image/x-icon" />
        <link href="https://fonts.googleapis.com/css?family=Allura" rel="stylesheet">
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/themes/base/all.css" rel="stylesheet" />
        <link href="~/Content/sidebar.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
        <script src="~/Scripts/jquery-3.1.1.min.js"></script>
        <script src="~/Scripts/bootstrap.js"></script>
        <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
        <script src="~/Scripts/Chart.min.js"></script>
        <script src="~/Scripts/Chart.PieceLabel.min.js"></script>
        <script src="~/Scripts/arcnet.simple.mask.min.js"></script>
    </head>
    <body class="principal">
        <div class="container body-content">
            <div class="estilo_exibicao">
                <p><span class="glyphicon glyphicon-th-list"></span> <span class="glyphicon glyphicon-th-large"></span></p>
            </div>
            <nav class="navbar navbar-inverse navbar-fixed-top">
                <ul class="nav navbar-brand">
                    <li class="add_game">Games</li>
                </ul>
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        @{Html.RenderAction("Menu", "Jquery");}
                        <div class="col-sm-2 col-md-2">
                            <form class="navbar-form" role="search">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Buscar" name="busca" id="busca">
                                    <span id="lista_resultados_busca" style="display:none"></span>
                                </div>
                            </form>
                        </div>
                        <i class="fa fa-table fa-inverse fa-2x" id="exportar" style="margin-top: 16px; cursor: pointer"></i>
                        <i class="fa fa-circle-o-notch fa-inverse fa-spin fa-2x fa-fw" style="display: none"></i>
                    </div>
                </div>
            </nav>
            @RenderBody()
        </div>
    </body>
</html>